import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.join(__dirname, "convex_export_data");
if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

const now = Date.now();
const hash = (pwd) => "seed_hash_" + pwd;

const data = {
  users: [
    {
      _id: "user_admin_1",
      email: "poornima@gmail.com",
      phone: "+91 9876543200",
      passwordHash: hash("poornima"),
      salt: "salt_admin",
      role: "admin",
      isActive: true,
      createdAt: now - 3600000 * 24 * 30,
      updatedAt: now,
    },
    {
      _id: "user_farmer_1",
      email: "raj.kumar@agriconnect.com",
      phone: "+91 9876543210",
      passwordHash: hash("farmer123"),
      salt: "salt_f1",
      role: "farmer",
      isActive: true,
      createdAt: now - 3600000 * 24 * 15,
      updatedAt: now,
    },
    {
      _id: "user_farmer_2",
      email: "priya.sharma@agriconnect.com",
      phone: "+91 9876543211",
      passwordHash: hash("farmer123"),
      salt: "salt_f2",
      role: "farmer",
      isActive: true,
      createdAt: now - 3600000 * 24 * 10,
      updatedAt: now,
    },
    {
      _id: "user_farmer_3",
      email: "arun.patel@agriconnect.com",
      phone: "+91 9876543212",
      passwordHash: hash("farmer123"),
      salt: "salt_f3",
      role: "farmer",
      isActive: true,
      createdAt: now - 3600000 * 24 * 8,
      updatedAt: now,
    },
    {
      _id: "user_farmer_4",
      email: "meena.devi@agriconnect.com",
      phone: "+91 9876543213",
      passwordHash: hash("farmer123"),
      salt: "salt_f4",
      role: "farmer",
      isActive: true,
      createdAt: now - 3600000 * 24 * 5,
      updatedAt: now,
    },
    {
      _id: "user_company_1",
      email: "procure@abcfoods.com",
      phone: "+91 9123456780",
      passwordHash: hash("company123"),
      salt: "salt_c1",
      role: "company",
      isActive: true,
      createdAt: now - 3600000 * 24 * 20,
      updatedAt: now,
    },
    {
      _id: "user_company_2",
      email: "contact@greenfresh.com",
      phone: "+91 9123456781",
      passwordHash: hash("company123"),
      salt: "salt_c2",
      role: "company",
      isActive: true,
      createdAt: now - 3600000 * 24 * 18,
      updatedAt: now,
    },
    {
      _id: "user_company_3",
      email: "trade@tamilagro.com",
      phone: "+91 9123456782",
      passwordHash: hash("company123"),
      salt: "salt_c3",
      role: "company",
      isActive: true,
      createdAt: now - 3600000 * 24 * 12,
      updatedAt: now,
    },
  ],
  farmers: [
    {
      _id: "farmer_profile_1",
      userId: "user_farmer_1",
      fullName: "Raj Kumar",
      phone: "+91 9876543210",
      email: "raj.kumar@agriconnect.com",
      profileImage: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=300",
      village: "Seithur",
      district: "Virudhunagar",
      state: "Tamil Nadu",
      farmSize: 12,
      farmSizeUnit: "Acres",
      description: "Progressive farmer cultivating high-yield organic tomatoes, onions and groundnuts.",
      createdAt: now - 3600000 * 24 * 15,
      updatedAt: now,
    },
    {
      _id: "farmer_profile_2",
      userId: "user_farmer_2",
      fullName: "Priya Sharma",
      phone: "+91 9876543211",
      email: "priya.sharma@agriconnect.com",
      profileImage: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300",
      village: "Kovilpatti",
      district: "Thoothukudi",
      state: "Tamil Nadu",
      farmSize: 8.5,
      farmSizeUnit: "Acres",
      description: "Specialized in drip-irrigated chilli, cotton, and organic millets.",
      createdAt: now - 3600000 * 24 * 10,
      updatedAt: now,
    },
    {
      _id: "farmer_profile_3",
      userId: "user_farmer_3",
      fullName: "Arun Patel",
      phone: "+91 9876543212",
      email: "arun.patel@agriconnect.com",
      profileImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300",
      village: "Alangulam",
      district: "Tenkasi",
      state: "Tamil Nadu",
      farmSize: 20,
      farmSizeUnit: "Acres",
      description: "Large scale paddy rice and premium Cavendish banana grower.",
      createdAt: now - 3600000 * 24 * 8,
      updatedAt: now,
    },
    {
      _id: "farmer_profile_4",
      userId: "user_farmer_4",
      fullName: "Meena Devi",
      phone: "+91 9876543213",
      email: "meena.devi@agriconnect.com",
      profileImage: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=300",
      village: "Usilampatti",
      district: "Madurai",
      state: "Tamil Nadu",
      farmSize: 6,
      farmSizeUnit: "Acres",
      description: "Quality producer of organic potatoes and fresh seasonal vegetables.",
      createdAt: now - 3600000 * 24 * 5,
      updatedAt: now,
    },
  ],
  companies: [
    {
      _id: "company_profile_1",
      userId: "user_company_1",
      companyName: "ABC Foods Pvt Ltd",
      email: "procure@abcfoods.com",
      phone: "+91 9123456780",
      logo: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?auto=format&fit=crop&q=80&w=300",
      companyType: "Food Processor",
      address: "142 SIDCO Industrial Estate",
      district: "Virudhunagar",
      state: "Tamil Nadu",
      description: "Leading agro-processing and sauce manufacturing unit sourcing fresh farm produce.",
      website: "https://abcfoods-agro.example.com",
      createdAt: now - 3600000 * 24 * 20,
      updatedAt: now,
    },
    {
      _id: "company_profile_2",
      userId: "user_company_2",
      companyName: "GreenFresh Agri Logistics",
      email: "contact@greenfresh.com",
      phone: "+91 9123456781",
      logo: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=300",
      companyType: "Wholesaler & Exporter",
      address: "88 Ring Road Agro Park",
      district: "Madurai",
      state: "Tamil Nadu",
      description: "Direct farm-to-supermarket cold chain distributor supplying 200+ retail stores.",
      website: "https://greenfresh-logistics.example.com",
      createdAt: now - 3600000 * 24 * 18,
      updatedAt: now,
    },
    {
      _id: "company_profile_3",
      userId: "user_company_3",
      companyName: "Tamil Agro Industries",
      email: "trade@tamilagro.com",
      phone: "+91 9123456782",
      logo: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&q=80&w=300",
      companyType: "Manufacturer",
      address: "55 Sipcot Industrial Complex",
      district: "Thoothukudi",
      state: "Tamil Nadu",
      description: "Industrial processor of cotton yarns, seed oil extraction, and bulk flour milling.",
      website: "https://tamilagroind.example.com",
      createdAt: now - 3600000 * 24 * 12,
      updatedAt: now,
    },
  ],
  crops: [
    {
      _id: "crop_1",
      farmerId: "user_farmer_1",
      farmerProfileId: "farmer_profile_1",
      farmerName: "Raj Kumar",
      cropName: "Tomato",
      variety: "Shivam Hybrid & Organic Country",
      quantity: 1500,
      unit: "kg",
      expectedPrice: 28,
      priceUnit: "per kg",
      harvestDate: "2026-10-10",
      location: "Seithur Farm Gate",
      district: "Virudhunagar",
      state: "Tamil Nadu",
      quality: "Grade A",
      description: "Freshly harvested firm red tomatoes with high shelf-life, pesticide residue free.",
      image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&q=80&w=400",
      status: "available",
      createdAt: now - 3600000 * 24 * 2,
      updatedAt: now,
    },
    {
      _id: "crop_2",
      farmerId: "user_farmer_1",
      farmerProfileId: "farmer_profile_1",
      farmerName: "Raj Kumar",
      cropName: "Onion",
      variety: "Bellary Red Medium",
      quantity: 1000,
      unit: "kg",
      expectedPrice: 35,
      priceUnit: "per kg",
      harvestDate: "2026-10-15",
      location: "Rajapalayam Mandi Road",
      district: "Virudhunagar",
      state: "Tamil Nadu",
      quality: "Grade A",
      description: "Properly cured, dry skinned and pungent onions sorted for commercial processing.",
      image: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&q=80&w=400",
      status: "available",
      createdAt: now - 3600000 * 24 * 3,
      updatedAt: now,
    },
    {
      _id: "crop_3",
      farmerId: "user_farmer_2",
      farmerProfileId: "farmer_profile_2",
      farmerName: "Priya Sharma",
      cropName: "Chilli",
      variety: "Guntur S4 Hot Red",
      quantity: 500,
      unit: "kg",
      expectedPrice: 180,
      priceUnit: "per kg",
      harvestDate: "2026-09-30",
      location: "Kovilpatti Highway Farm",
      district: "Thoothukudi",
      state: "Tamil Nadu",
      quality: "Organic Certified",
      description: "Sun-dried fiery red chillies, low moisture and zero aflatoxin contamination.",
      image: "https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&q=80&w=400",
      status: "available",
      createdAt: now - 3600000 * 24 * 1,
      updatedAt: now,
    },
    {
      _id: "crop_4",
      farmerId: "user_farmer_3",
      farmerProfileId: "farmer_profile_3",
      farmerName: "Arun Patel",
      cropName: "Rice",
      variety: "Ponni Raw Rice (Aged 1 yr)",
      quantity: 5000,
      unit: "kg",
      expectedPrice: 52,
      priceUnit: "per kg",
      harvestDate: "2026-08-20",
      location: "Tenkasi Rice Mill Road",
      district: "Tenkasi",
      state: "Tamil Nadu",
      quality: "Grade A",
      description: "Single-polish fine grain aromatic Ponni rice ready in 50kg bags.",
      image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=400",
      status: "available",
      createdAt: now - 3600000 * 24 * 4,
      updatedAt: now,
    },
    {
      _id: "crop_5",
      farmerId: "user_farmer_4",
      farmerProfileId: "farmer_profile_4",
      farmerName: "Meena Devi",
      cropName: "Potato",
      variety: "Kufri Jyoti Processing Grade",
      quantity: 3000,
      unit: "kg",
      expectedPrice: 22,
      priceUnit: "per kg",
      harvestDate: "2026-10-05",
      location: "Usilampatti Cold Depot",
      district: "Madurai",
      state: "Tamil Nadu",
      quality: "Grade A",
      description: "Uniform 45mm+ size potatoes with low sugar content ideal for chips & french fries.",
      image: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&q=80&w=400",
      status: "available",
      createdAt: now - 3600000 * 24 * 2,
      updatedAt: now,
    },
  ],
  demands: [
    {
      _id: "demand_1",
      companyId: "user_company_1",
      companyProfileId: "company_profile_1",
      companyName: "ABC Foods Pvt Ltd",
      cropName: "Tomato",
      variety: "Processing Grade (Firm)",
      requiredQuantity: 10000,
      unit: "kg",
      offeredPriceMin: 25,
      offeredPriceMax: 30,
      priceUnit: "per kg",
      requiredDate: "2026-10-25",
      deliveryLocation: "ABC Foods Plant 2, Virudhunagar",
      district: "Virudhunagar",
      state: "Tamil Nadu",
      qualityRequirements: "High TSS > 4.5, dark red coloration, free from mold or punctures.",
      description: "Urgent requirement for paste and puree processing. Daily unloading available.",
      status: "active",
      createdAt: now - 3600000 * 24 * 3,
      updatedAt: now,
    },
    {
      _id: "demand_2",
      companyId: "user_company_2",
      companyProfileId: "company_profile_2",
      companyName: "GreenFresh Agri Logistics",
      cropName: "Onion",
      variety: "Bellary or Nashik Red 40mm+",
      requiredQuantity: 8000,
      unit: "kg",
      offeredPriceMin: 32,
      offeredPriceMax: 38,
      priceUnit: "per kg",
      requiredDate: "2026-10-20",
      deliveryLocation: "GreenFresh Central Warehouse, Madurai",
      district: "Madurai",
      state: "Tamil Nadu",
      qualityRequirements: "Double skinned, sorted, dry neck, 45-55mm grading.",
      description: "Bulk supply required for supermarket distribution. Immediate settlement.",
      status: "active",
      createdAt: now - 3600000 * 24 * 2,
      updatedAt: now,
    },
    {
      _id: "demand_3",
      companyId: "user_company_3",
      companyProfileId: "company_profile_3",
      companyName: "Tamil Agro Industries",
      cropName: "Cotton",
      variety: "Bt Cotton Shankar 6",
      requiredQuantity: 15000,
      unit: "kg",
      offeredPriceMin: 72,
      offeredPriceMax: 80,
      priceUnit: "per kg",
      requiredDate: "2026-11-15",
      deliveryLocation: "Sipcot Ginning Unit, Thoothukudi",
      district: "Thoothukudi",
      state: "Tamil Nadu",
      qualityRequirements: "29mm staple length, moisture < 8%, zero foreign contamination.",
      description: "Long staple cotton required for spinning mill contract.",
      status: "active",
      createdAt: now - 3600000 * 24 * 5,
      updatedAt: now,
    },
  ],
};

for (const [table, records] of Object.entries(data)) {
  const jsonlPath = path.join(outDir, `${table}.jsonl`);
  const jsonPath = path.join(outDir, `${table}.json`);
  const lines = records.map((r) => JSON.stringify(r)).join("\n");
  fs.writeFileSync(jsonlPath, lines, "utf8");
  fs.writeFileSync(jsonPath, JSON.stringify(records, null, 2), "utf8");
  console.log(`Exported ${records.length} records to ${table}.jsonl and ${table}.json`);
}

console.log("All Convex export data generated successfully in convex_export_data/");
